version: '3'

services:
  easyswoole:
    # build:
    #   context: .docker
    #   dockerfile: easyswoole/Dockerfile
    image: easyswoole/easyswoole3
    container_name: jeason_easyswoole
    restart: "no"
    tty: true
    volumes:
      - ./src-easyswoole:/src-easyswoole:delegated
    ports:
      - 9501:9501


  # laravel_db:
  #   image: mysql:8
  #   command: --default-authentication-plugin=mysql_native_password
  #   container_name: ${COMPOSE_PROJECT_NAME}_laravel_db
  #   restart: always
  #   volumes:
  #     - laravel-db:/var/lib/mysql
  #   environment:
  #     - MYSQL_DATABASE=${DB_DATABASE}
  #     - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}

# volumes:
#   laravel-db:
#   laravel-storage:
